# Generated by Django 4.2.5 on 2024-05-08 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0002_completed_remove_task_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Completed',
        ),
    ]
